# MEMBER = MGDB_SASTRA_MINGGU.members
# WORK = MGDB_SASTRA_MINGGU.works
# COUNT_NOTIF = MGDB_SASTRA_MINGGU.count_notifs
from config.mongo import MGDB_SEMINAR_CALENDAR

ADMIN = MGDB_SEMINAR_CALENDAR.admins
